# config/config.yaml
model_params:
  objective: "binary:logistic"
  max_depth: 6
  learning_rate: 0.1
  n_estimators: 100
  min_child_weight: 1
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42

data_paths:
  train: "data/churn-bigml-80.csv"
  test: "data/churn-bigml-20.csv"

mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "churn_prediction"
  model_name: "churn_model"
  registered_model_name: "churn_model"

api:
  host: "0.0.0.0"
  port: 8000
  debug: false

monitoring:
  elasticsearch_host: "http://elasticsearch:9200"
  kibana_host: "http://localhost:5601"
  prediction_index: "churn-predictions"
  metrics_index: "model-metrics"
  alert_thresholds:
    drift_threshold: 0.1
    latency_threshold: 1000
    accuracy_threshold: 0.9

features:
  selected_features:
    - "Total day minutes"
    - "Customer service calls"
    - "International plan"
    - "Total intl minutes"
    - "Total intl calls"
    - "Total eve minutes"
    - "Number vmail messages"
    - "Voice mail plan"
  categorical_features:
    - "International plan"
    - "Voice mail plan"